### ISSUE TITLE
Action bar parsing error

### ISSUE THREAD

**Issue by Kolobok125040** [MisterCheezeCake/SkyblockTweaks#5]
[HERE](https://raw.githubusercontent.com/Kolobok125040/nothing_special/refs/heads/main/100k_lines_log) full log file.

**Comment by MisterCheezeCake** [comment]
Fixed in https://github.com/MisterCheezeCake/SkyblockTweaks/commit/c7e78856f0a3425eb9b7ebc8f5e3405e1b9e035a and 0.1.0-Alpha.8
