### ISSUE TITLE
Suggestion: Rift time and hearts in rift

### ISSUE THREAD

**Issue by nshjck** [MisterCheezeCake/SkyblockTweaks#6]
I think the option to have hearts only disabled outside of the rift and a HUD element for rift time would be pretty useful as currently if I'm doing vampire slayer I have to toggle my hearts back on in settings when going in and out of the rift

**Comment by MisterCheezeCake** [comment]
This is a good idea, and I'll add it in the next release

**Comment by nshjck** [comment]
Awesome thanks for the quick response <3
